module.exports = [
  'A4',
  'Active Ankle',
  'adidas',
  'adidas Athletics',
  'adidas Originals',
  'All Star',
  'Alleson',
  'American Stitch',
  'Arena',
  'ASICS Tiger',
  'ASICS®',
  'ASO',
  'Atec',
  'Athletic Specialties',
  'Augusta Sportswear',
  'Avia',
  'Baden',
  'Badger Sporting Good',
  'Badger Sportswear',
  'Bandulu',
  'Battle Sports',
  'Birkenstock',
  'Blazer',
  'Brooks',
  'Camelbak',
  'Cascade',
  'Champion',
  'Champro',
  'Chattanooga',
  'Chinatown Market',
  'Classroom Uniforms',
  'CleenFreek',
  'Cliff Keen',
  'Columbia',
  'Converse',
  'Cramer',
  'Crocs',
  'Crossover Culture',
  'CSG',
  'Cutters',
  'DeMarini',
  'Diamond',
  'Dolfin',
  'DonJoy Performance',
  'Douglas',
  'Dudley',
  'Eastbay',
  'Easton',
  'Ellesse',
  'Evoshield',
  'Fila',
  'Fisher Athletic',
  'Franklin',
  'Funko',
  'G-Form',
  'Gatorade',
  'Gildan',
  'Gill',
  "Glover's",
  'Go Sports',
  'Goalrilla',
  'Grip Gear Sports',
  'Hanes',
  'Harbinger',
  'Heelys',
  'Herschel',
  'HOKA ONE ONE',
  'Holloway',
  'Hudson',
  'Hurley',
  'Ice20',
  'IKONICK Jeff Cole',
  'Imprints',
  'Inov-8',
  'ISLIDE',
  'Ivy Park',
  'J-BIZ',
  'Jaeger Sports',
  'JanSport',
  'Jordan',
  'Just Don',
  'K-Swiss',
  'Kaepa',
  'Kinney Shoes',
  'Korney Boards Aides',
  'Kwik Goal',
  'Lacoste',
  "Levi's",
  'Lifeline',
  'Louis De Guzman',
  'Louisville Slugger',
  'Mad Hits Enterprises',
  'Majestic',
  'Mark V',
  'Markwort',
  'Marucci',
  'Maverik Lacrosse',
  'McDavid',
  'MinkPink',
  'Mitchell & Ness',
  'Mizuno',
  'Molten',
  'Mudkat Sports',
  'Mueller',
  'New Balance',
  'New Era',
  'Nfinity',
  'NFL',
  'Nike',
  'Nike SB',
  'Oakley',
  'Omni-Lite',
  'Palladium',
  'Palmgard',
  'Pelican',
  'PGA Tour',
  'PJ Tucker',
  'Port & Company',
  'Pro Performance',
  'Pro Standard',
  'Pro-Tec',
  'ProFeet',
  'PROHITTER',
  'PSD',
  'PUMA',
  'Rawlings',
  'Reebok',
  'RIP-IT',
  'Robic',
  'Rudis',
  'Runners Point',
  'Russell',
  'Sanmar',
  'Saranac',
  'Saucony',
  'Schutt',
  'Scoremaster',
  'Sean John',
  'Shadowman Sports',
  'Shock Doctor',
  'Signature Lacrosse',
  'SKLZ',
  'Softball Excellence',
  'Sophia Chang',
  'Spalding',
  'Speedo',
  'SPORT-TEK',
  'Sportstar',
  'SPRI',
  'Stance',
  'Staple Design',
  'Starter',
  'Storelli Sports',
  'STX',
  'Super Heroic',
  'Swingbuster',
  'Tachikara',
  'Tanner Tees',
  'TaylorMade',
  'Teva',
  'THE',
  'The North Face',
  'Timberland',
  'Tommy Hilfiger',
  'Traplord JV',
  'TriggerPoint',
  'Twin City',
  'TYR',
  'UAS',
  'UGG',
  'Umbro',
  'Under Armour',
  'Under Armour Team',
  'Vans',
  'Victus',
  'Warrior',
  'Wilson',
  'Wizard',
  'Woolworth',
  'Zamst'
]
